# Generated by Django 5.0.1 on 2024-02-02 02:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='membershipDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
