# Generated by Django 5.0.1 on 2024-02-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0002_remove_bookdetail_id_alter_bookdetail_bookid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='bookID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
