# Generated by Django 5.0.1 on 2024-02-02 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0003_remove_book_id_alter_book_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='bookID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookmanager.book', verbose_name='bookID'),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='detailsID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
